dependencies:
    - smartcontractkit/chainlink@1.13.0
    - OpenZeppelin/openzeppelin-contracts@4.5.0

compiler:
    solc:
        remappings:
            - "@chainlink=smartcontractkit/chainlink@1.13.0"
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"

networks:
    mainnet-fork:
        eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
